spring:
  application:
    name: bookstore
  profiles:
    active: dev
  batch:
    job:
      enabled: false
    initialize-schema: always

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bookstore_local_db
    username: user
    password: 1234
    driverClassName: org.postgresql.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    user:
      password: admin
      name: admin

server:
  port: 80
  servlet:
    context-path: /bookstore