INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Alice in Wonderland', 'Lewis Caroll', 'Fairytales', 356);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Clean Code', 'Robert Martin', 'Studies', 460);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Learning Java', 'Katy Sierra', 'Studies', 460);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'War and Peace', 'Lev Tolstoy', 'Classics', 2542);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Mernieku Laiki', 'Reinis un Matis Kaudzits', 'Classics', 700);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Song of Solomon', 'Tony Morrison', 'Novel', 1000);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Ulysses', 'James Joyce', 'Science', 460);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Lord of the Rings', 'J.R.R. Tolkien', 'Adventures', 1500);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Don Quixote', 'Miguel de Cervantes', 'Classics', 682);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Golden Compass', 'Philip Pullman', 'Fantasy', 520);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Catch-22', 'Joseph Heller', 'Detective', 482);
INSERT INTO book(title, author, genre, pages_count) VALUES ( '1984', 'George Orvell', 'Fantasy', 496);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Picture of Dorian Gray', 'Oscar Wilde', 'Classics', 759);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Lolita', 'Vladimir Nabokov', 'Classics', 514);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Moby-Dick', 'Herman Melville', 'Classics', 396);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Pride and Prejudice', 'Jane Austen', 'Classics', 541);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Great Expectations', 'Charles Dickens', 'Classics', 460);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Wolf Hall', 'Hilary Mantel', 'Classics', 612);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Frankenstein', 'Mary Shelley', 'Classics', 460);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Anna Karenina', 'Lev Tolstoy', 'Classics', 1012);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Lord of the Flies', 'William Golding', 'Classics', 789);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Great Gatsby', 'F. Scott Fitzgerald', 'Classics', 475);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'On the Road', 'Jack Kerouac', 'Adventures', 652);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'To Kill A Mockingbird ', 'Harper Lee', 'Classics', 854);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Catcher in the Rye', 'JD Salinger', 'Classics', 756);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Midnight’s Children', 'Salman Rushdie', 'Classics', 932);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Grapes Of Wrath', 'John Steinbeck', 'Classics', 125);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Jane Eyre', 'Charlotte Brontë', 'Classics', 451);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Mrs. Dalloway', 'Virginia Woolf', 'Classics', 556);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'A Passage to India', 'EM Forster', 'Classics', 332);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Brave New World', 'Aldous Huxley', 'Classics', 771);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Things Fall Apart', 'Chinua Achebe', 'Classics', 554);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Prime of Miss Jean Brodie', 'Muriel Spark', 'Classics', 156);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'Classics', 547);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Animal Farm', 'George Orwell', 'Studies', 265);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Beloved', 'Toni Morrison', 'Classics', 460);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Invisible Man', 'Ralph Ellison', 'Detective', 365);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Slaughterhouse-Five', 'Kurt Vonnegut', 'Classics', 322);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Stranger', 'Albert Camus', 'Classics', 387);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Robinson Crusoe', 'Daniel Defoe', 'Classics', 465);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Count of Monte Cristo', 'Alexandre Dumas', 'Classics', 485);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'David Copperfield', 'Charles Dickens', 'Studies', 474);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Wuthering Heights', 'Emily Brontë', 'Classics', 414);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Little Women', 'Louisa M Alcott ', 'Classics', 517);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Call of the Wild', 'Jack London', 'Adventures', 852);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Wind in the Willows', 'Kenneth Grahame', 'Classics', 583);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Scoop', 'Evelyn Waugh', 'Detective', 371);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Big Sleep', 'Raymond Chandler', 'Classics', 369);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Lucky Jim', 'Kingsley Amis', 'Studies', 189);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'If on a Winter’s Night a Traveller', 'Italo Calvino', 'Adventures', 279);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'A Bend in the River', 'V. S. Naipaul', 'Detective', 298);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Housekeeping', 'Marilynne Robinson', 'Classics', 336);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'His Dark Materials', 'Philip Pullman', 'Fantasy', 399);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Hitchhiker’s Guide to the Galaxy', 'Douglas Adams', 'Classics', 345);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Middlemarch', 'George Eliot', 'Studies', 388);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Portnoy’s Complaint', 'Philip Roth', 'Classics', 375);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Age of Innocence', 'Edith Wharton', 'Classics', 325);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'The Sun Also Rises', 'Ernest Hemingway', 'Classics', 318);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'To the Lighthouse', 'Virginia Woolf', 'Classics', 485);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'White Noise', 'Don DeLillo', 'Classics', 428);
INSERT INTO book(title, author, genre, pages_count) VALUES ( 'Pale Fire', 'Vladimir Nabokov', 'Classics', 511);